--- # NFS SERVER SETUP EXAMPLE
- hosts: appserver
  user: test
  sudo: yes
  connection: ssh
  gather_facts: yes
  vars:
    distribution: RedHat
    nfsutils_pkg: nfs-utils
    nfslibs_pkg: nfs-utils-lib
    nfsserver_service: nfs-server
    nfslock_service: nfs-lock
    nfsmap_service: nfs-idmap
    rpcbind_service: rpcbind
    export_path: /var/share
    client_path: /mnt/remote
  tasks:
  - name: Install all the NFS Server Utilities, Services and Libraries
    yum: pkg={{ item }} state=latest
    with_items:
    - "{{ nfsutils_pkg }}"
    - "{{ nfslibs_pkg }}"
  - name: Copy the export file to the remote server
    copy: src=files/exports.template dest=/etc/exports owner=root group=root mode=644
    notify: 
    - StartServerServices
    - InstallClientPackages
    - CreateClientMount
    - ClientMountServerResource
    - TestServerAvailability
  handlers:
  - name: StartServerServices
    service: name={{ item }} state=restarted
    with_items:
    - "{{ rpcbind_service }}"
    - "{{ nfsserver_service }}"
    - "{{ nfslock_service }}"
    - "{{ nfsmap_service }}"
  - name: InstallClientPackages
    yum: pkg={{ item }} state=latest
    with_items:
    - "{{ nfsutils_pkg }}"
    - "{{ nfslibs_pkg }}"
    delegate_to: 127.0.0.1
    notify: StartClientServices
  - name: StartClientServices
    service: name={{ item }} state=restarted
    with_items:
    - "{{ rpcbind_service }}"
    - "{{ nfslock_service }}"
    - "{{ nfsmap_service }}"
    delegate_to: 127.0.0.1
  - name: CreateClientMount
    file: path={{ client_path }} state=directory mode=755
    delegate_to: 127.0.0.1
  - name: ClientMountServerResource
    shell: mount -t nfs tcox5.mylabserver.com:{{ export_path }} {{ client_path }}
    register: result
    delegate_to: 127.0.0.1
  - name: TestServerAvailability
    debug: var=result
