--- # Master Playbook for DB Servers
- hosts: appserver
  user: test
  sudo: yes
  connection: ssh
  pre_tasks:
  - name: When did the ROLE start
    raw: date > /home/test/startofrole.log
  roles:
  - dbservers
  post_tasks:
  - name: When did the ROLE end
    raw: date > /home/test/endofrole.log
