--- # MYSQL_USER MODULE DEMO
- hosts: appserver
  user: test
  sudo: yes
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Install the MySQL Python Support Library
    yum: pkg=MySQL-python state=latest
  - name: Create a new user called BOB and give him all access
    mysql_user: name=bob password=123password priv=*.*:ALL state=present login_user=root login_password=password123
