--- # STAT MODULE EXAMPLE
- hosts: apacheweb
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - stat: path=/home/test/abc
    register: p
  - debug: msg="The Path Exists and is a Directory"
    when: p.stat.isdir is defined and p.stat.isdir 
